version: '3'
services:
  streamlit-app:
    image: python:3.9-slim
    container_name: streamlit-container
    ports:
      - "80:8501"
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "apt update && apt install libgomp1 && pip install --upgrade pip && pip install -r requirements.txt && streamlit run app.py"
